---
- include_vars:         "../../../sensitive-ansible/roles/{{ role_name }}/vars/kdc_db_master_key.yml"
- include_tasks:        '../tasks/install_packages.yml'
- include_tasks:        '../tasks/install_files.yml'
- include_tasks:        '../tasks/template_files.yml'
- include_tasks:        '../tasks/create_krb5_realm.yml'
- include_tasks:        '../tasks/enable_services.yml'
- include_tasks:        '../tasks/restart_services.yml'
  when:                 install_files_result.changed 
                        or template_files_result.changed
                        or create_krb5_realm_result.changed
- include_tasks:        '../tasks/start_services.yml'
